export const RESULT_SUMMARY_REVEAL_DELAY_MS = 2200;
export const SQL_REVEAL_INITIAL_DELAY_MS = 5000;
export const SQL_REVEAL_TARGET_DURATION_MS = 7200;

export const ASK_ANSWER_COMPLETION_DELAY_MS =
  SQL_REVEAL_INITIAL_DELAY_MS + SQL_REVEAL_TARGET_DURATION_MS;
export const ASK_STATE_COMPLETION_DELAY_MS = 900;
